### ISSUE TITLE
Google Contacts - Dark Style changes background on Twitter and Facebook

### ISSUE THREAD

**Issue by rrthomas** [Devo7v/UserCSS#1]
I'm using the latest version of Stylus and the Google Contacts Dark Style (0.2.0).

I use Twitter's own Dark style, and have no Stylus styles configured for twitter.com or facebook.com. Somehow, when I switch on Google Contacts Dark Style, the background of twitter.com and of facebook.com is set to Firefox's value for `browser.display.background_color`. With the style off (and Stylus still active, with Google Bar Dark and Google Calendar Dark), everything works as normal.

**Comment by rrthomas** [comment]
Thanks very much for your work on the dark styles! I hope they will soon be unnecessary (with Google and others providing their own dark styles), but until then it is a great service that you perform.

**Comment by rrthomas** [comment]
I see that "Google Contacts - Dark Style" is marked "active" on twitter.com, but I can't see why, as that URL is not listed in the configuration.

**Comment by rrthomas** [comment]
I think I found the bug: after the most recent update, the old version of the style is applied to all sites, because it is outside the scope of the per-site directive. If I delete the old version CSS, Twitter & Facebook go back to normal. (I guess that may not be the right solution, but it will do for me for now.)

**Comment by teohhanhui** [comment]
Looks like it's a misplaced closing brace?

**Comment by Devo7v** [comment]
Do either of you have a link to access the old Google Contacts?  I can't seem to access it anymore, so if it's no longer accessible, I'll just remove the code.

**Comment by rrthomas** [comment]
@Devo7v I don't!

**Comment by Devo7v** [comment]
I'll go ahead an remove the obsolete code then.
