### ISSUE TITLE
Text color for recurrence options in deletion dialog

### ISSUE THREAD

**Issue by rrthomas** [Devo7v/UserCSS#3]
I could not find CSS that was obviously intended to apply to the text in the recurrence dialog when deleting an event.

I added `.SDtMeb` as follows to fix it, but I'm not sure this is the correct way to do it:

```
*=======Custom recurrence popup=======*/
…
    /*Other text*/
    .PbnGhe, .SDtMeb {
        color: var(--gcal-primary-text-color) !important;
    }
```

**Comment by Devo7v** [comment]
Could you create a pull request and I'll review and approve if it makes sense.

**Comment by rrthomas** [comment]
I'm sorry, I don't have any real idea where the relevant style should go, but I'll create a PR anyway.

**Comment by Devo7v** [comment]
I updated the style to update when the user changes the system theme and fixed this issue as well.  If you find anything else, please submit a pull request and let me know.
