### ISSUE TITLE
Google Voice dialer and chat sections white

### ISSUE THREAD

**Issue by gh7468** [Devo7v/UserCSS#6]
![gvdark](https://user-images.githubusercontent.com/107718160/174391151-c2bf521b-3054-42fb-a859-730cdb2b8985.jpg)

Maybe I'm doing something wrong but it says I'm updated to the latest version which seems to match what you have in the latest fixes?

Sorry if I'm messing something up.

**Comment by Devo7v** [comment]
Looks like Google changed a lot of class names.  There are a lot of changes that will need to be made to the style.  It's going to take me a few days to get it fixed up.  In the meantime you can change line 231 to this to at least get messages in better shape:
```
/*Overall Background and Text*/
md-content, body, .gvInfiniteScroll-root, .gvMessageListHeader-messageHeader, .md-body-1 {
    background-color: var(--gvoice-background-color) !important;
    color: var(--gvoice-white) !important;
}
```

**Comment by Devo7v** [comment]
I'm fairly certain that this has all been fixed.  Please confirm and close.  After a couple weeks I will close this issue if I don't hear anything.
